### ISSUE TITLE
KeyError: 'd'

### ISSUE THREAD

**Issue by beat4ocean** [Tencent/TencentPretrain#92]
python finetune/run_classifier.py --pretrained_model_path models/roberta-base-finetuned-dianping-chinese/pytorch_model.bin \
                                   --vocab_path models/google_zh_vocab.txt \
                                   --config_path models/sbert/base_config.json \
                                   --output_model_path models/test_model.bin \
                                   --train_path datasets/book_review/train.tsv \
                                   --dev_path datasets/book_review/dev.tsv \
                                   --test_path datasets/book_review/test.tsv \
                                   --epochs_num 3 \
                                   --batch_size 32 \
                                   --learning_rate 3e-5 \
                                   --seq_length 512

Traceback (most recent call last):
  File "/home/almalinux/TencentPretrain/finetune/run_classifier.py", line 366, in <module>
    main()
  File "/home/almalinux/TencentPretrain/finetune/run_classifier.py", line 291, in main
    model = Classifier(args)
  File "/home/almalinux/TencentPretrain/finetune/run_classifier.py", line 33, in __init__
    tmp_emb = str2embedding[embedding_name](args, len(args.tokenizer.vocab))
KeyError: 'd'

**Comment by BenBill2077** [comment]
I have similar problem:
 File "/my_TencentPretrain-main/finetune/run_speech2text.py", line 311, in <module>
    main()
  File "/my_TencentPretrain-main/finetune/run_speech2text.py", line 239, in main
    model = Speech2text(args)
  File "/my_TencentPretrain-main/finetune/run_speech2text.py", line 33, in __init__
    tmp_emb = str2embedding[embedding_name](args, len(args.tokenizer.vocab))
KeyError: 'w'
Have you solved the problem?
